spring:
  datasource:
    url: jdbc:mysql://localhost:33306/zaojubang?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: duchao123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update